// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpFI7CrpyOW0Gr2gZfr8061kI7o1xEjy0',
    appId: '1:472216810580:web:f8eaea04cf69a88ff929c1',
    messagingSenderId: '472216810580',
    projectId: 'job-jungle',
    authDomain: 'job-jungle.firebaseapp.com',
    storageBucket: 'job-jungle.appspot.com',
    measurementId: 'G-R2Q4BC5CZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF174v4lfE9EIUIZ3Kn0A_qdzq2Y8xgtI',
    appId: '1:472216810580:android:f30aea237ce9c846f929c1',
    messagingSenderId: '472216810580',
    projectId: 'job-jungle',
    storageBucket: 'job-jungle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2CWnVHrBW5KjzgyKwbxCDdGNI6pOnAQY',
    appId: '1:472216810580:ios:6494c60b9289df4ff929c1',
    messagingSenderId: '472216810580',
    projectId: 'job-jungle',
    storageBucket: 'job-jungle.appspot.com',
    iosClientId: '472216810580-2g7r78eq1520g71knjq0eu9ed189buuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobJungleFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2CWnVHrBW5KjzgyKwbxCDdGNI6pOnAQY',
    appId: '1:472216810580:ios:6494c60b9289df4ff929c1',
    messagingSenderId: '472216810580',
    projectId: 'job-jungle',
    storageBucket: 'job-jungle.appspot.com',
    iosClientId: '472216810580-2g7r78eq1520g71knjq0eu9ed189buuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobJungleFlutter',
  );
}
